name: mayr_events
description: "A lightweight, expressive event and listener system for Dart, inspired by Laravel's event architecture."
version: 2.1.0
homepage: https://mayrlabs.com
repository: https://github.com/MayR-Labs/dart_events
issue_tracker: https://github.com/MayR-Labs/dart_events/issues
documentation: https://github.com/MayR-Labs/dart_events/wiki

environment:
  sdk: ^3.9.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

topics:
  - event
  - listener
  - architecture
  - dart
  - pub
