name: mayr_events
description: "A lightweight, expressive event and listener system for Dart, inspired by Laravel's event architecture."
version: 1.1.0
homepage: https://github.com/MayR-Labs/dart_events
repository: https://github.com/MayR-Labs/dart_events
issue_tracker: https://github.com/MayR-Labs/dart_events/issues
documentation: https://github.com/MayR-Labs/dart_events/wiki
LICENSE: MIT

environment:
  sdk: ^3.9.2

# dependencies:

dev_dependencies:
  test: ^1.25.0
  lints: ^5.0.0

topics:
  - event
  - listener
  - architecture
  - dart
  - event-bus
